# Generated by Django 4.1.3 on 2023-07-27 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Тип тренировки')),
            ],
            options={
                'verbose_name': 'Тип тренировки',
                'verbose_name_plural': 'Типы тренировки',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время начала')),
                ('finished_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время окончания')),
                ('distance', models.FloatField(default=0, verbose_name='Дистанция')),
                ('steps_num', models.IntegerField(default=0, verbose_name='Количество шагов')),
                ('completed', models.BooleanField(default=False, verbose_name='Завершение тренировки')),
                ('reminder', models.BooleanField(default=False, verbose_name='Напоминание о тренировке')),
                ('raiting', models.SmallIntegerField(default=None, verbose_name='Рейтинг')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to=settings.AUTH_USER_MODEL, verbose_name='Автор тренировки')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainings', to='trainings.trainingtype', verbose_name='Тип тренировки')),
            ],
            options={
                'verbose_name': 'Тренировка',
                'verbose_name_plural': 'Тренировки',
                'ordering': ['started_at'],
            },
        ),
    ]
