# Generated by Django 4.1.3 on 2023-07-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='raiting',
            field=models.SmallIntegerField(blank=True, default=None, verbose_name='Рейтинг'),
        ),
    ]
