# Generated by Django 4.1.3 on 2023-07-27 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0002_alter_training_raiting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='raiting',
            field=models.SmallIntegerField(default=None, null=True, verbose_name='Рейтинг'),
        ),
    ]
