# Generated by Django 4.2 on 2023-08-09 10:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0004_alter_training_raiting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='finished_at',
            field=models.DateTimeField(db_index=True, default=datetime.datetime.now, verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='training',
            name='started_at',
            field=models.DateTimeField(db_index=True, default=datetime.datetime.now, verbose_name='Время начала'),
        ),
        migrations.AlterField(
            model_name='trainingtype',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Тип тренировки'),
        ),
    ]
